#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &
# Swayidle
DIR=$HOME/.config/hypr/bg
PICS=($(ls ${DIR}))
RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}
swayidle -w \
	timeout 300 'swaylock -f -c 000000' \
	timeout 360 'hyprctl dispatch dpms off' \
	resume 'hyprctl dispatch dpms on' \
	before-sleep "swaylock --clock -f --indicator --effect-blur 7x5 -i '$RANDOMPIC'" &
#insync start &
#dropbox &
#telegram-desktop &
#discord &
#nm-applet --indicator
